name: Cross-Browser Test Flow

on:
  push:
    branches: ['**']

jobs:
  cross-browser-test:
    name: Cross-Browser Tests
    runs-on: ubuntu-latest

    steps:
      - name: install Firefox stable
        run: |
          sudo apt-get update
          sudo apt-get install firefox
      - uses: actions/checkout@v2
      - name: Set up Node (14)
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Bump Node memory limit
        run: echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
      - name: Test setup and yarn install
        run: |
          cp config/ci.config.json config/project.json
          yarn
      - name: yarn build
        run: yarn build
      - name: Run Cross Browser tests
        run: xvfb-run yarn test:cross-browser
